### ISSUE TITLE
HiKey - Add support for high speed UARTS

### ISSUE THREAD

**Issue by ldts** [96boards/linux#18]
Note that despite these UARTs not quite being ARM type UARTs they identify themselves as ARM-v1s.  This complicates the up-streaming of the necessary extensions via vendor abstractions. 

There will be a number of uart features to be delivered under this issue:

1) clock: the high speed uarts need to be feed a high frequency clock in order to perform at rates above 115Kbps- this directly impact uart clients (like bluetooth 96boards/linux#20)

2) fifo-size: the default value provided by the driver is no longer valid (is 64 now)

3) power management

4) dma bindings and default settings.

**Comment by ldts** [comment]
if this is going to take time to be delivered, I'd propose we go with this until a proper fix is put in place. This at least does not polute the amba driver 


    [jramirez@calypso-2 v8r2-kernel.git (hw-init *$)]$ git diff drivers/clk/hisilicon/clk-hi6220.c
    diff --git a/drivers/clk/hisilicon/clk-hi6220.c b/drivers/clk/hisilicon/clk-hi6220.c
    index 29c7165..f387bbc 100644
    --- a/drivers/clk/hisilicon/clk-hi6220.c
    +++ b/drivers/clk/hisilicon/clk-hi6220.c
    @@ -179,6 +179,7 @@ static struct hi6220_divider_clock hi6220_div_clks_sys[] __initdata = {
    static void __init hi6220_clk_sys_init(struct device_node *np)
     {
            struct hisi_clock_data *clk_data;
    +       struct clk *clk_a, *clk_b;
     
            clk_data = hisi_clk_init(np, HI6220_SYS_NR_CLKS);
            if (!clk_data)
    @@ -192,6 +193,21 @@ static void __init hi6220_clk_sys_init(struct device_node *np)
     
            hi6220_clk_register_divider(hi6220_div_clks_sys,
                            ARRAY_SIZE(hi6220_div_clks_sys), clk_data);
    +
    +       /* enable high speed clock on UART1 mux */
    +       clk_a = clk_get_parent(clk_data->clk_data.clks[HI6220_UART1_PCLK]);
    +       if (IS_ERR_OR_NULL(clk_a)) {
    +               printk("clk_a NULL \n");
    +               return;
    +       }
    +
    +       clk_b = clk_get_parent_by_index(clk_a, 1);
    +       if (IS_ERR_OR_NULL(clk_b)) {
    +               printk("clk_a NULL \n");
    +               return;
    +       }
    +
    +       clk_set_parent(clk_a, clk_b);
     }
     CLK_OF_DECLARE(hi6220_clk_sys, "hisilicon,hi6220-clock-sys", hi6220_clk_sys_init);

**Comment by docularxu** [comment]
I like your pull request: https://github.com/96boards/linux/pull/21

Wangfei (Huawei
w.f@huawei.com ) knew about this issue for 3Mbps uart1. Should we invite him here. And assign to him instead of me? :)

**Comment by ldts** [comment]
sure, I just dont know his githubid.
