### ISSUE TITLE
Bluetooth at 3MBps 

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/linux#3]
Bluetooth at 3MBps is currently not supported on the board.

**Comment by ldts** [comment]
Diagnosis: after the bluetooth stack receives the acknowledge from the firmware that is ok to increase the baudrate, the UIM set the termios of amba-pl011.c to 3mbps. At that poing the high speed UART seems to stop responding and communication with the BT firmware is lost.

**Comment by fboudra** [comment]
This issue was moved to 96boards/bugs#3
