### ISSUE TITLE
AMBA UARTs fifo depth on device tree

### ISSUE THREAD

**Issue by ldts** [96boards/linux#5]
The high speed UARTs in the SoC have ARM ids. 
However, for these UARTS, the fifo depth is defined in the device tree
amba-pl011.c needs to be modified to read the fifo depth from the firmware table.

**Comment by koenkooi** [comment]
'firmware table' being the DT or the TI bluetooth table?

**Comment by ldts** [comment]
DT

**Comment by koenkooi** [comment]
To recap:

1) hi6220-hikey.dts has:
                     uart2: uart@f7112000 {
                        compatible = "arm,pl011", "arm,primecell";
                         [..]
                        fifo-deep-size = <64>;

2) Neither Documentation/devicetree/bindings/serial/pl011.txt nor Documentation/devicetree/bindings/arm/primecell.txt mentions fifo-deep-size. It sounds like engrish to me, I guess 'fifo-depth' would make more sense.

3) drivers/tty/serial/amba-pl011.c doesn't use OF to read the fifosize, but does:
                    return amba_rev(dev) < 3 ? 16 : 32;

So amba-pl011.c needs to be modified to either use OF methods for the fifosize or fix the get_fifosize_arm(struct amba_device *dev) method to support 64 as well.

Did I catch everything in the above summary?

**Comment by ldts** [comment]
yes - and thanks for bringing in clarity

**Comment by ldts** [comment]
diff --git a/drivers/tty/serial/amba-pl011.c b/drivers/tty/serial/amba-pl011.c
index 02016fc..e9754de 100644
--- a/drivers/tty/serial/amba-pl011.c
+++ b/drivers/tty/serial/amba-pl011.c
@@ -84,6 +84,13 @@ struct vendor_data {
 
 static unsigned int get_fifosize_arm(struct amba_device *dev)
 {
+       unsigned int psize;
+       const void *prop;
+
+       prop = of_get_property(dev->dev.of_node, "fifo-deep-size", &psize);
+       if (prop)
+               return of_read_ulong(prop, 1);
+
        return amba_rev(dev) < 3 ? 16 : 32;
 }

**Comment by fboudra** [comment]
This issue was moved to 96boards/bugs#5
