### ISSUE TITLE
Linaro account permissions wrong

### ISSUE THREAD

**Issue by gcgrey** [96boards/linux#6]
Debian default user account is linaro/linaro. 
In release and 118 snapshot user:group is root:root - needs to be changed to linaro:linaro

**Comment by fboudra** [comment]
fixed in [build 119](https://builds.96boards.org/snapshots/hikey/debian/119)

It isn't a kernel issue, it's make_ext4fs issue that doesn't preserve permissions.

**Comment by fboudra** [comment]
This issue was moved to 96boards/bugs#6
